# Generated by Django 3.1.6 on 2021-02-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20210215_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoapp',
            options={'ordering': ['task_id']},
        ),
        migrations.RenameField(
            model_name='todoapp',
            old_name='taskid',
            new_name='task_id',
        ),
    ]
