# Generated by Django 2.2.10 on 2020-04-03 13:54

from django.db import migrations, models
import userprofile.ultilities


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=userprofile.ultilities.user_directory_path),
        ),
    ]
