# Generated by Django 2.2.10 on 2020-05-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('userprofile', '0002_auto_20200403_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(to='courses.Subject'),
        ),
    ]
