# Generated by Django 2.2.10 on 2020-05-13 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='city',
        ),
    ]
