# Generated by Django 2.2.10 on 2020-06-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200624_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
    ]
