# Generated by Django 4.2.4 on 2023-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_exam_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
