# Generated by Django 4.2.4 on 2023-08-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_exam_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='season',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
