# Generated by Django 2.2.10 on 2020-08-21 08:16

import apps_math.ultilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsMath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to=apps_math.ultilities.apps_math_image_path_front, verbose_name='front image')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to=apps_math.ultilities.apps_math_image_path_top, verbose_name='top image')),
                ('web', models.TextField(max_length=500, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
