# Generated by Django 2.2.10 on 2020-08-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsmath',
            old_name='app_name',
            new_name='appname',
        ),
        migrations.AddField(
            model_name='appsmath',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
