# Generated by Django 2.2.10 on 2020-08-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0002_auto_20200823_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
