# Generated by Django 2.2.10 on 2020-08-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0003_function_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='appname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='appname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath'),
        ),
    ]
