# Generated by Django 2.2.10 on 2020-08-25 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0004_auto_20200824_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RightBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeftBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HorizontalLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
