# Generated by Django 2.2.10 on 2020-08-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0005_horizontallabel_leftbound_rightbound_title_verticallabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsmath',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appsmath',
            name='web',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
