# Generated by Django 2.2.10 on 2020-08-30 23:04

import apps_math.ultilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0006_auto_20200830_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsmath',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps_math.ultilities.apps_math_image_path_right, verbose_name='right image'),
        ),
    ]
