# Generated by Django 2.2.10 on 2020-08-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0007_appsmath_right_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsmath',
            name='right_image_web',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
