# Generated by Django 2.2.10 on 2020-09-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0008_appsmath_right_image_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
