# Generated by Django 2.2.10 on 2020-09-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0009_initialvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialValue',
            new_name='InitialFunctionValue',
        ),
    ]
