# Generated by Django 2.2.10 on 2020-09-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0010_auto_20200914_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialDerivativeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('latex', models.CharField(max_length=200, null=True)),
                ('appname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_math.AppsMath')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
