# Generated by Django 2.2.10 on 2020-11-21 04:06

import apps_math.ultilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_math', '0012_auto_20201120_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsmath',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps_math.ultilities.apps_math_image_path_front, verbose_name='front image'),
        ),
        migrations.AlterField(
            model_name='appsmath',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps_math.ultilities.apps_math_image_path_right, verbose_name='right image'),
        ),
        migrations.AlterField(
            model_name='appsmath',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps_math.ultilities.apps_math_image_path_top, verbose_name='top image'),
        ),
    ]
