# Generated by Django 2.2.10 on 2020-08-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='web',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
