# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # https://app.vagrantup.com/bento/boxes/ubuntu-18.04
    config.vm.box = "bento/ubuntu-18.04"

    # Configure a private network.
    # Run services from 0.0.0.0:$port in the box.
    # Connect from the host at $private_ip:$port.
    config.vm.network "private_network", type: "dhcp"

    # Virtualbox-managed VMs
    # https://www.vagrantup.com/docs/providers/virtualbox/configuration.html
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.gui = false
    end

    # Parallels-managed VMs (Mac-only)
    # https://parallels.github.io/vagrant-parallels/docs/configuration.html
    config.vm.provider "parallels" do |prl|
      prl.cpus = 2
      prl.memory = 4096
      # Install the guest tools manually after provisioning:
      #     sudo ptiagent-cmd
      #     exit
      #     vagrant reload
      # This is to get around this bug: https://github.com/Parallels/vagrant-parallels/issues/350
      prl.check_guest_tools = false
      prl.update_guest_tools = false
    end

    # Upgrade as root.
    config.vm.provision "shell", privileged: true, path: "provisioners/ubuntu_root_upgrade.sh"

    # Provision as root.
    config.vm.provision "shell", privileged: true, path: "provisioners/ubuntu_root.sh"

    # Provision more as user.
    config.vm.provision "shell", privileged: false, path: "provisioners/ubuntu_user.sh"

    # Cleanup and reboot.
    config.vm.provision "shell", privileged: true, path: "provisioners/ubuntu_root_cleanup.sh"

end
