# Generated by Django 2.2.10 on 2020-05-12 07:59

import courses.ultilities
from django.db import migrations, models
import django.db.models.deletion
import courses.ultilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(max_length=500, blank=False, null=True)),
                ('front_image', models.ImageField(blank=True, null=True,
                                                  upload_to=courses.ultilities.subject_image_path_front, verbose_name='front image')),
                ('top_image', models.ImageField(blank=True, null=True,
                                                upload_to=courses.ultilities.subject_image_path_top, verbose_name='top image')),
                ('web', models.TextField(max_length=500, blank=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True,
                                          upload_to=courses.ultilities.public_file_path, verbose_name="public file")),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
