# Generated by Django 3.1.4 on 2021-02-01 07:55

import cloudinary_storage.storage
import courses.ultilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=courses.ultilities.public_file_path, verbose_name='public file'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='web',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
